/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-08-18 12:42:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPageInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript -->\r\n");
      out.write("    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\" integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- DaumPostcode import -->\r\n");
      out.write("    <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- kakaoMap Api -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=dc023166bbc9c4e8ae23818cf48006fe&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/user/mypageInsert.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/dinner41.css\">\r\n");
      out.write("\r\n");
      out.write("    <title>My Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-light light_green\">\r\n");
      out.write("\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <!--사용자 위치-->\r\n");
      out.write("    <div class=\"btn-group\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-dark dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("            <span>서울특별시 봉천동</span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"dropdown-menu\">\r\n");
      out.write("            <a class=\"dropdown-item\" href=\"#\">주소 변경하기</a>\r\n");
      out.write("            <div class=\"dropdown-divider\"></div>\r\n");
      out.write("            <a class=\"dropdown-item\" href=\"#\">현재 위치 기준</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gm/cart\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/icons/shopping-bag-solid.svg\" class=\"cart\" alt=\"no picture\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <!--메뉴-->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("        <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">내정보 보기</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">주문 내역</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ALL/1/qna\">1:1 문의</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\"> </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\"> </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">로그아웃</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!--Content-->\r\n");
      out.write("<div>\r\n");
      out.write("    <!--제목-->\r\n");
      out.write("    <div class=\"container-fluid text-center\" style=\"margin-top: 15pt\">\r\n");
      out.write("        <img src=\"../../images/1인의만찬.png\" class=\"img-title\" alt=\"no title\"/>\r\n");
      out.write("        <h4>마이페이지</h4>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr/>\r\n");
      out.write("\r\n");
      out.write("    <!--내정보 수정 폼-->\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage\" id=\"update_form\" method=\"post\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"userName\">이름</label>\r\n");
      out.write("            <input type=\"text\" name=\"name\" class=\"form-control \" id=\"userName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"userEmail\">이메일</label>\r\n");
      out.write("            <input type=\"email\" name=\"email\" class=\"form-control\" id=\"userEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("        </div>\r\n");

	kr.co.dinner41.vo.UserVO user=(kr.co.dinner41.vo.UserVO)session.getAttribute("loginUser");
	String phone=user.getPhone();
	int phoneLength=phone.length();
	String phone1=phone.substring(0, 3);
	String phone2=phone.substring(3, phoneLength-4);
	String phone3=phone.substring(phoneLength-4,phoneLength);

      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"phoneNumber\">전화번호</label>\r\n");
      out.write("            <div id=\"phoneNumber\">\r\n");
      out.write("                <input type=\"tel\" value=\"");
      out.print(phone1 );
      out.write("\" name=\"phone1\" class=\"form-control\" id=\"phoneNumber1\" style=\"width: 30% ;float: left\" >\r\n");
      out.write("                <p style=\"width: 5% ;float: left;text-align: center\">-</p>\r\n");
      out.write("                <input type=\"tel\" value=\"");
      out.print(phone2 );
      out.write("\" name=\"phone2\" class=\"form-control\" id=\"phoneNumber2\" style=\"width: 30% ;float: left\" >\r\n");
      out.write("                <p style=\"width: 5% ;float: left ; text-align: center\">-</p>\r\n");
      out.write("                <input type=\"tel\" value=\"");
      out.print(phone3 );
      out.write("\" name=\"phone3\" class=\"form-control\" id=\"phoneNumber3\" style=\"width: 30% ;\" >\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"address\">거주지</label>\r\n");
      out.write("            <div id=\"address\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-success two_button\" id=\"search_button\">주소 찾기</button>\r\n");
      out.write("                <input type=\"text\" name=\"address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control margin_up\" placeholder=\"주소\" id=\"user_address\"/>\r\n");
      out.write("                <input type=\"text\" name=\"subAddress\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.subAddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control margin_up\" placeholder=\"상세주소\" id=\"user_sub_address\"/>\r\n");
      out.write("\t\t\t\t<div id=\"wrap\" style=\"display:none;border:2px solid #CFE3A1;width:503px;height:300px;margin:5px 0;position:absolute; overflow:auto;\"></div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"latitude\" id=\"user_latitude\" name=\"latitude\" value=\"\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"longitude\" id=\"user_longitude\" name=\"longitude\" value=\"\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 비밀번호 수정버튼을 누르면 비밀번호 수정하는 걸로 바꿈  -->\r\n");
      out.write("        <button type=\"button\" id=\"update_password_button\" class=\"btn btn-success two_button\" style=\"margin-bottom: 20pt;\">비밀번호 수정하기</button>\r\n");
      out.write("\r\n");
      out.write("<!--  \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"exampleInputPassword1\">비밀번호</label>\r\n");
      out.write("            <input type=\"password\" name=\"newPassword\" class=\"form-control\" id=\"exampleInputPassword1\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\" style=\"margin-bottom: 20pt\">\r\n");
      out.write("            <label for=\"exampleInputPassword2\">비밀번호 확인</label>\r\n");
      out.write("            <input type=\"password\" name=\"newPasswordConfirm\" class=\"form-control\" id=\"exampleInputPassword2\">\r\n");
      out.write("            <small id=\"passhelp\" class=\"form-text text-muted\">내정보 수정을 위해서는 비밀번호 입력이 필요합니다.</small>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("-->\r\n");
      out.write("        <div id=\"InputNewPassword\" class=\"form-group\" style=\"display:none\">\r\n");
      out.write("            <label for=\"exampleInputPassword1\">비밀번호</label>\r\n");
      out.write("            <input type=\"password\" name=\"newPassword\" class=\"form-control\" id=\"exampleInputPassword1\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"InputNewPasswordConfirm\" class=\"form-group\" style=\"margin-bottom: 20pt; display:none\">\r\n");
      out.write("            <label for=\"exampleInputPassword2\">비밀번호 확인</label>\r\n");
      out.write("            <input type=\"password\" name=\"newPasswordConfirm\" class=\"form-control\" id=\"exampleInputPassword2\">\r\n");
      out.write("            <small id=\"passhelp\" class=\"form-text text-muted\">내정보 수정을 위해서는 비밀번호 입력이 필요합니다.</small>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"margin_first\">\r\n");
      out.write("            <button type=\"button\" id=\"complete_update_button\" class=\"btn btn-success two_button\">수정완료</button>\r\n");
      out.write("            <button type=\"button\" id=\"goBackButton\" class=\"btn btn-success two_button float-right\">수정취소</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div class=\"last_block\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
